name: Print Secret

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print Repo Secret
        env:
          MY_SECRET: ${{ secrets.MY_REPO_SECRET }}
        run: |
          echo "Accessing a secret value:"
          # This will mask the secret value in the log, so it won't be displayed plainly.
          echo "Secret accessed: $MY_REPO_SECRET"

      - name: Print Env Secret
        env:
          MY_SECRET: ${{ secrets.MY_ENVIRONMENT_SECRET }}
        run: |
          echo "Accessing a secret value:"
          # This will mask the secret value in the log, so it won't be displayed plainly.
          echo "Secret accessed: $MY_ENVIRONMENT_SECRET"
